Repository Heptagram-Project/website, pull requests merged in 2021-11, with the labels that each got.

#80 We can launch the website now !
  404.html
  README.md
  commands.html
  heptagram-devs.html
  index.html
  js/main.js
  privacy-policy.html
  terms-of-service.html
Labels: duplicate

#102 Run NPM commands on Gitpod start
  .gitpod.yml
  package-lock.json
Labels: priority: medium

#105 Fix Dependabot Alerts
  package-lock.json
  package.json
Labels: priority: high
